yapp/presenter/urls.py
from django.urls import path

from presenter.views import LiveModeView, AllPicturesView, PlainPictureView, RandomPictureView, UploadPictureView, \
    PlainVideoView, RandomMediaObjectView

urlpatterns = [
    path('live/', LiveModeView.as_view(), name='live'),
    path('pictures/random', RandomPictureView.as_view(), name='random_picture'),
    path('pictures/<int:picture_id>/plain', PlainPictureView.as_view(), name='plain_picture'),
    path('pictures/', AllPicturesView.as_view(), name='all_pictures'),
    path('pictures/upload/', UploadPictureView.as_view(), name='upload_picture'),

    # path('videos/random/', RandomVideoView.as_view(), name='random_video'),
    path('videos/<int:video_id>/plain/', PlainVideoView.as_view(), name='plain_video'),
    # path('videos/', AllVideoView.as_view(), name='all_videos'),
    # path('videos/upload/', UploadVideoView.as_view(), name='upload_video'),
    #
    path('random/', RandomMediaObjectView.as_view(), name='random_media_object'),
]

yapp/yapp/urls.py
from django.contrib import admin
from django.urls import path, include

from presenter.views import LiveModeView

urlpatterns = [
    path('', LiveModeView.as_view()),
    path('admin/', admin.site.urls),
    path('presenter/', include(('presenter.urls', 'presenter'), namespace='presenter')),
]

yapp/presenter/models.py
from django.db import models


class MediaObject(models.Model):
    """
    Base class for picture and video objects
    """

    filePath = models.FileField()
    title = models.CharField(
        max_length=200,
        blank=True,
        default=None,
        null=True,
    )
    mimeType= models.CharField(
        max_length=200,
        blank=True,
        default=None,
        null=True,
    )
    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title if self.title else 'No Title'

    class Meta:
        abstract = True


class Picture(MediaObject):
    """
    Model class for the uploaded/ submitted party pictures
    """


class Video(MediaObject):
    """
    Model class for the uploaded/ submitted party pictures
    """

yapp/presenter/forms.py
from django import forms
from django.utils.translation import gettext

from presenter.models import Picture


class PictureUploadForm(forms.ModelForm):
    """
    Model form for uploading pictures
    """

    filePath = forms.FileField(
        label=gettext('File'),
    )
    title = forms.CharField(
        required=False,
        label=gettext('Title')
    )
    likes = forms.HiddenInput()
    dislikes = forms.HiddenInput()
    timestamp = forms.HiddenInput()
    mimeType = forms.HiddenInput()

    class Meta:
        model = Picture
        fields = ('title', 'filePath',)

yapp/presenter/views.py
import os
import random

from django.http import HttpResponseNotFound, HttpResponse, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse_lazy
from django.views import View
from django.utils.translation import gettext

from yapp.settings.base import WS_BROKER_PORT, WS_BROKER_ADDRESS, BOT_SETTINGS
from presenter.forms import PictureUploadForm
from presenter.models import Picture, Video
from presenter.tables import PictureTable


class LiveModeView(View):
    """
    View class for the start page
    """
    title = 'Live View'

    def get(self, request):
        fullscreen = request.GET.get('fullscreen', None)
        context = {
            'title': self.title,
            'ws_broker_port': WS_BROKER_PORT,
            'ws_broker_address': WS_BROKER_ADDRESS,
            'bot_contact': BOT_SETTINGS['Contact'],
            'seconds_per_picture': int(request.GET.get('secondsPerPicture', '3'))
        }
        template = 'presenter/live_fullscreen.html' if fullscreen else 'presenter/live.html'
        return render(request, template, context)


class AllPicturesView(View):
    """
    View class for list of all pictures
    """
    title = gettext('All Pictures')

    def get(self, request):
        context = {
            'title': self.title,
            'table': PictureTable(Picture.objects.all().order_by(request.GET.get('sort', '-timestamp')))
        }
        return render(request, 'presenter/all.html', context)


class PlainPictureView(View):
    """
    View class for providing only the picture
    """

    def get(self, request, picture_id):
        picture_obj = get_object_or_404(Picture, pk=picture_id)
        if not os.path.exists(picture_obj.filePath.path):
            return HttpResponseNotFound()
        with open(picture_obj.filePath.path, 'rb') as fh:
            resp = HttpResponse(fh.read(), content_type=picture_obj.mimeType)
        return resp


class PlainVideoView(View):
    """
    View class for providing only the picture
    """

    def get(self, request, video_id):
        video_obj = get_object_or_404(Video, pk=video_id)
        if not os.path.exists(video_obj.filePath.path):
            return HttpResponseNotFound()
        with open(video_obj.filePath.path, 'rb') as fh:
            resp = HttpResponse(fh.read(), content_type=video_obj.mimeType)
        return resp


class RandomPictureView(View):
    """
    View class for the provision of a random picture
    """

    def get(self, request):
        all_pictures = list(Picture.objects.all())
        while len(all_pictures) > 0:
            picture_obj = all_pictures[random.randint(0, len(all_pictures) - 1)]
            if not os.path.exists(picture_obj.filePath.path):
                continue
            if request.GET.get('json', None):
                return JsonResponse({
                    'url': str(reverse_lazy('presenter:plain_picture', args=[picture_obj.id])),
                    'title': picture_obj.title,
                    'likes': picture_obj.likes,
                    'dislikes': picture_obj.dislikes,
                })

            with open(picture_obj.filePath.path, 'rb') as fh:
                resp = HttpResponse(fh.read(), content_type=picture_obj.mimeType)
            return resp
        return HttpResponseNotFound()


class RandomMediaObjectView(View):
    """
    View class for the provision of a random picture or video
    """
    def get(self, request):
        all_media_objects = list(Picture.objects.all()) + list(Video.objects.all())
        while len(all_media_objects) > 0:
            media_obj = all_media_objects[random.randint(0, len(all_media_objects) - 1)]
            if not os.path.exists(media_obj.filePath.path):
                continue
            if request.GET.get('json', None):
                url_alias = 'presenter:' + ('plain_picture' if isinstance(media_obj,Picture) else 'plain_video' )
                return JsonResponse({
                    'url': str(reverse_lazy(url_alias, args=[media_obj.id])),
                    'title': media_obj.title,
                    'likes': media_obj.likes,
                    'dislikes': media_obj.dislikes,
                    'mimeType': media_obj.mimeType,
                })

            with open(media_obj.filePath.path, 'rb') as fh:
                resp = HttpResponse(fh.read(), content_type=media_obj.mimeType)
            return resp
        return HttpResponseNotFound()


class UploadPictureView(View):
    """
    View class for manual uploading of a picture
    """
    title = gettext('Manual Upload')

    def get(self, request):
        context = {
            'title': self.title,
            'form': PictureUploadForm(),
        }
        return render(request, 'presenter/upload.html', context)

    def post(self, request):
        form = PictureUploadForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            response_class = HttpResponse
            notification = (True, gettext('Picture saved'))
        else:
            notification = (False, gettext('Form contains invalid input.'))
            response_class = HttpResponseBadRequest

        context = {
            'form': form,
            'title': self.title,
            'notification': notification,
        }
        template = loader.get_template('presenter/upload.html')
        return response_class(template.render(context, request))

yapp/presenter/templates/presenter/all.html
{% extends 'presenter/blank.html' %}
{% load bootstrap4 %}
{% load static %}
{% load render_table from django_tables2 %}

{% block title %}
{{ title }}
{% endblock %}



{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="row">
        <div class="col-12">
            {% render_table table %}
        </div>
    </div>



{% endblock %}

yapp/presenter/templates/presenter/all_pictures.html
{% extends 'presenter/blank.html' %}
{% load bootstrap4 %}
{% load static %}
{% load render_table from django_tables2 %}

{% block title %}
{{ title }}
{% endblock %}



{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="row">
        <div class="col-12">
            {% render_table table %}
        </div>
    </div>



{% endblock %}

yapp/presenter/templates/presenter/blank.html
{% load bootstrap4 %}
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Yet Another Picture Presenter (YAPP) - {% block title %}{% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static "presenter/vendor/fontawesome-free/css/all.min.css" %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static "presenter/css/sb-admin-2.min.css" %}" rel="stylesheet">

    <link rel="shortcut icon" type="image/png" href="{% static 'presenter/img/logo.png' %}"/>
    {% block head %}

    {% endblock %}

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    {% include "presenter/sidebar.html" %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Begin Page Content -->
            <div class="container-fluid">
            <br/><br/>
            {% block content %}

            {% endblock %}
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->

        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Bootstrap core JavaScript-->
<script src="{% static "presenter/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "presenter/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static "presenter/vendor/jquery-easing/jquery.easing.min.js" %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static "presenter/js/sb-admin-2.min.js" %}"></script>


</body>

</html>

yapp/presenter/templates/presenter/live.html
{% extends 'presenter/blank.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{{ title }}
{% endblock %}

{% block head %}
    <script src="{% static "presenter/js/live.js" %}"></script>
    <script src="{% static "presenter/js/ajax.js" %}"></script>
    <script src="{% static "presenter/js/ws.js" %}"></script>
{% endblock %}

{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    <div class="row">
        <div style="width: 100%;" class="col-6">
            <h3>Live Show</h3>
            <img id="live_picture" style="max-width: 100%; max-height: 600px;" src="{% url "presenter:random_picture" %}">
        </div>
        <div class="col-6">
            <h3>Telegram {% trans "Contact" %}</h3>
        <img style="position: relative;" src="{% static "bots/img/telegram-contact.png" %}">
        <br/>
        <a href="{{ bot_contact }}">{{ bot_contact }}</a>
   </div>
    </div>
    <br/>

    <div class="row">
        <div class="col-12">
            <a href="{% url "presenter:live" %}?fullscreen=1"><button type="button" style="width: 100%;" class="btn btn-lg btn-info">Vollbild-Modus</button></a>
        </div>
    </div>

    <script>
        init_ws("ws://{{ ws_broker_address }}:{{ ws_broker_port }}",ws_on_receive_callback);
        init_ajax_update({{ seconds_per_picture }}, "{% url "presenter:random_picture" %}?json=1");
    </script>

{% endblock %}

yapp/presenter/templates/presenter/live_fullscreen.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <script src="{% static "presenter/js/live_fullscreen.js" %}"></script>
        <script src="{% static "presenter/js/ajax.js" %}"></script>
        <script src="{% static "presenter/js/ws.js" %}"></script>
        <title>YAPP- Live View - Fullscreen</title>
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static "presenter/css/sb-admin-2.min.css" %}" rel="stylesheet">
    </head>
    <body id="body" style="background-color: #464646;background-attachment: fixed;background-position: center center;background-image:url({% url "presenter:random_picture" %});background-repeat:no-repeat; background-size: contain;" >

    <video style=" position: fixed; left:0;top: 0; height: 0; width: 0;">
        <source id="video_source" src="{% static "presenter/img/dummy.mp4" %}" type="video/mp4">
    </video>
    <h1 id="title" style="width: 100%; text-align: center; position: absolute; bottom: 1px; color: #00e6fb; font-weight: bolder;"></h1>
    <div style="position: absolute; bottom:10px; right: 10px; text-align: center;">
        <img  width="100" src="{% static "bots/img/telegram-contact.png" %}">
        <br/>
        <a href="{{ bot_contact }}">{{ bot_contact }}</a>
   </div>
    <script>
        init_ws("ws://{{ ws_broker_address }}:{{ ws_broker_port }}",ws_on_receive_callback);
        init_ajax_update({{ seconds_per_picture }}, "{% url "presenter:random_media_object" %}?json=1");
    </script>

    </body>
</html>

yapp/presenter/templates/presenter/sidebar.html
{% load static %}
{% load i18n %}
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-danger sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url "presenter:live" %}" style="height: 140px;">
            <div class="sidebar-brand-icon">
                <img src="{% static "presenter/img/logo.png" %}" style="height: 50px;">

            <br/><br/>
            <div class="sidebar-brand-text mx-3">YAPP</div>
            </div>
        </a>
        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url "presenter:live" %}">
                <i class="fas fa-fw  fa-camera-retro"></i>
                <span>Live View</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Nav Item - Pages Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url "presenter:all_pictures" %}">
                <i class="fas fa-fw fa-copy"></i>
                <span>{% trans "All Pictures" %}</span>
            </a>
        </li>

        <hr class="sidebar-divider">

        <!-- Nav Item - Utilities Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url "presenter:upload_picture" %}">
                <i class="fas fa-image"></i>
                <span>{% trans "Manual Upload" %}</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">


    </ul>
    <!-- End of Sidebar -->

yapp/presenter/templates/presenter/upload.html
{% extends 'presenter/blank.html' %}
{% load bootstrap4 %}
{% load static %}
{% load i18n %}

{% block title %}
{{ title }}
{% endblock %}



{% block content %}
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ title }}</h1>
    </div>

    {% if notification %}
        {% if notification.0 %}
            <div class="card bg-success text-white shadow">
                <div class="card-body">{{ notification.1 }}</div>
            </div>
        {% else %}
            <div class="card bg-danger text-white shadow">
                <div class="card-body">{{ notification.1 }}</div>
            </div>
        {% endif %}
        <br/>
    {% endif %}


    <div class="row">
        <div class="col-12">
            <form action="{% url "presenter:upload_picture" %}" method="post" class="form" enctype='multipart/form-data'>
                {% csrf_token %}
                {% bootstrap_form form%}
                {% buttons %}
                    <button type="submit" style="width: 100%;" class="btn btn-lg btn-info">{% trans "Save" %}</button>
                {% endbuttons %}
            </form>

        </div>
    </div>



{% endblock %}